import type { Item } from '../types';

export const ITEMS: Record<string, Item> = {
  compass: {
    id: 'compass',
    name: 'Compass',
    description: 'Never get lost.',
    category: 'ESSENTIAL',
    width: 1,
    height: 1,
    icon: 'Compass',
    scoreValue: 10,
  },
  water_bottle: {
    id: 'water_bottle',
    name: 'Water Bottle',
    description: 'Hydration is key.',
    category: 'ESSENTIAL',
    width: 1,
    height: 2,
    icon: 'Droplets',
    scoreValue: 10,
  },
  rations: {
    id: 'rations',
    name: 'Rations',
    description: 'Dried food packs.',
    category: 'ESSENTIAL',
    width: 2,
    height: 2,
    icon: 'Package',
    scoreValue: 10,
  },
  map: {
    id: 'map',
    name: 'Trail Map',
    description: 'Know the path.',
    category: 'ESSENTIAL',
    width: 2,
    height: 2,
    icon: 'Map',
    scoreValue: 15,
  },
  flashlight: {
    id: 'flashlight',
    name: 'Flashlight',
    description: 'See in the dark.',
    category: 'TOOL',
    width: 1,
    height: 2,
    icon: 'Flashlight',
    scoreValue: 5,
  },
  rope: {
    id: 'rope',
    name: 'Climbing Rope',
    description: 'For steep cliffs.',
    category: 'TOOL',
    width: 2,
    height: 3, // Long item
    icon: 'Ratchet', // approximation
    scoreValue: 15,
  },
  knife: {
    id: 'knife',
    name: 'Pocket Knife',
    description: 'Versatile tool.',
    category: 'TOOL',
    width: 1,
    height: 1,
    icon: 'Scissors', // approximation
    scoreValue: 5,
  },
  first_aid: {
    id: 'first_aid',
    name: 'First Aid Kit',
    description: 'Patch up wounds.',
    category: 'SURVIVAL',
    width: 2,
    height: 2,
    icon: 'BriefcaseMedical',
    scoreValue: 20,
  },
  matches: {
    id: 'matches',
    name: 'Matches',
    description: 'Fire is life.',
    category: 'SURVIVAL',
    width: 1,
    height: 1,
    icon: 'Flame',
    scoreValue: 5,
  },
  sleeping_bag: {
    id: 'sleeping_bag',
    name: 'Sleeping Bag',
    description: 'Warm nights.',
    category: 'COMFORT',
    width: 2,
    height: 3,
    icon: 'Bed',
    scoreValue: 5,
  },
  rock: {
    id: 'rock',
    name: 'Heavy Rock',
    description: 'Just useless weight.',
    category: 'SABOTAGE',
    width: 2,
    height: 2,
    icon: 'Gem', // looks like a rock?
    scoreValue: -10,
  },
  broken_radio: {
    id: 'broken_radio',
    name: 'Broken Radio',
    description: 'Makes noise, does nothing.',
    category: 'SABOTAGE',
    width: 2,
    height: 1,
    icon: 'Radio',
    scoreValue: -5,
  },
};

export const GRID_SIZE = 8; // 8x8 grid for now
