import type { Item } from "../../types"
import { TIER_TARGETS, calcWeaponStats } from "../balancing"

export const basicWeapons: Record<string, Item> = {
  dagger: {
    id: "dagger",
    name: "Dagger",
    description: "Fast and efficient.",
    category: "WEAPON",
    width: 1,
    height: 2,
    icon: "Sword",
    rarity: "COMMON",
    triggerType: "ATTACK",
    combatStats: calcWeaponStats({
      dps: TIER_TARGETS.COMMON.dps,
      eps: TIER_TARGETS.COMMON.eps,
      baseCooldown: 0.8,
    }),
  },
  hatchet: {
    id: "hatchet",
    name: "Hatchet",
    description: "Heavy swings.",
    category: "WEAPON",
    width: 2,
    height: 2,
    shape: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 0, y: 1 },
    ],
    icon: "Axe",
    rarity: "COMMON",
    triggerType: "ATTACK",
    combatStats: calcWeaponStats({
      dps: TIER_TARGETS.COMMON.dps,
      eps: TIER_TARGETS.COMMON.eps,
      baseCooldown: 2.0,
    }),
  },
  wand_of_sparking: {
    id: "wand_of_sparking",
    name: "Wand of Sparking",
    description: "Magical sparks. Passive: +1 Mana Regen.",
    category: "WEAPON",
    width: 1,
    height: 2,
    icon: "Zap",
    rarity: "COMMON",
    triggerType: "ATTACK",
    combatStats: {
      ...calcWeaponStats({
        dps: TIER_TARGETS.COMMON.dps,
        mps: TIER_TARGETS.COMMON.mps,
        baseCooldown: 1.0,
      }),
      manaRegen: 1,
    },
  },
  broadsword: {
    id: "broadsword",
    name: "Broadsword",
    description: "Stronger but exhausting.",
    category: "WEAPON",
    width: 1,
    height: 3,
    icon: "Sword",
    rarity: "UNCOMMON",
    triggerType: "ATTACK",
    combatStats: calcWeaponStats({
      dps: TIER_TARGETS.UNCOMMON.dps,
      eps: TIER_TARGETS.UNCOMMON.eps,
      energyCost: 90,
    }),
  },
  staff_of_life: {
    id: "staff_of_life",
    name: "Staff of Life",
    description: "Life magic. Passive: +15 Max HP.",
    category: "WEAPON",
    width: 1,
    height: 3,
    icon: "Stick",
    rarity: "UNCOMMON",
    triggerType: "ATTACK",
    combatStats: {
      ...calcWeaponStats({
        dps: TIER_TARGETS.UNCOMMON.dps,
        mps: TIER_TARGETS.UNCOMMON.mps,
        baseCooldown: 1.0,
      }),
      maxHp: 15,
    },
  },
  warhammer: {
    id: "warhammer",
    name: "Warhammer",
    description: "Devastating but slow.",
    category: "WEAPON",
    width: 3,
    height: 3,
    shape: [
      { x: 0, y: 0 },
      { x: 1, y: 0 },
      { x: 2, y: 0 },
      { x: 1, y: 1 },
      { x: 1, y: 2 },
    ],
    icon: "Hammer",
    rarity: "RARE",
    triggerType: "ATTACK",
    combatStats: calcWeaponStats({
      dps: TIER_TARGETS.RARE.dps,
      eps: TIER_TARGETS.RARE.eps,
      energyCost: 100,
    }),
  },
  arcane_scepter: {
    id: "arcane_scepter",
    name: "Arcane Scepter",
    description: "Arcane mastery. Passive: +5 Mana Regen.",
    category: "WEAPON",
    width: 1,
    height: 3,
    icon: "Wand",
    rarity: "RARE",
    triggerType: "ATTACK",
    combatStats: {
      ...calcWeaponStats({
        dps: TIER_TARGETS.RARE.dps,
        mps: TIER_TARGETS.RARE.mps,
        baseCooldown: 0.8,
      }),
      manaRegen: 5,
    },
  },
}
