import type { Item } from "../../types"

export const craftableItems: Record<string, Item> = {
  shard_spikes: {
    id: "shard_spikes",
    name: "Spike Shard",
    description:
      "A long, sharp fragment. Adds reactive spikes to your defense.",
    category: "TOOL",
    width: 1,
    height: 3,
    icon: "Zap",
    rarity: "COMMON",
    triggerType: "PASSIVE",
    combatStats: {
      spikes: 3,
    },
  },
  shard_block: {
    id: "shard_block",
    name: "Block Shard",
    description: "A long, sturdy fragment. Adds minor block to your defense.",
    category: "TOOL",
    width: 1,
    height: 3,
    icon: "Square",
    rarity: "COMMON",
    triggerType: "PASSIVE",
    combatStats: {
      block: 5,
    },
  },
  rusty_dagger: {
    id: "rusty_dagger",
    name: "Rusty Dagger",
    description: "Old and dull. Better than nothing.",
    category: "WEAPON",
    width: 1,
    height: 2,
    icon: "Sword",
    rarity: "COMMON",
    triggerType: "ATTACK",
    combatStats: {
      damage: 4,
      baseCooldown: 1.0,
      energyCost: 10,
    },
  },
  cracked_wand: {
    id: "cracked_wand",
    name: "Cracked Wand",
    description: "Barely holds magic. Passive: +0.5 Mana Regen.",
    category: "WEAPON",
    width: 1,
    height: 2,
    icon: "Zap",
    rarity: "COMMON",
    triggerType: "ATTACK",
    combatStats: {
      damage: 3,
      manaCost: 8,
      baseCooldown: 1.2,
      manaRegen: 0.5,
    },
  },
  scrap_shield: {
    id: "scrap_shield",
    name: "Scrap Shield",
    description: "Thin metal sheet. Provides minor protection.",
    category: "TOOL",
    width: 2,
    height: 2,
    icon: "Shield",
    rarity: "COMMON",
    triggerType: "SHIELD",
    combatStats: {
      block: 8,
      baseCooldown: 4.0,
      energyCost: 5,
    },
  },
  spiked_shield: {
    id: "spiked_shield",
    name: "Spiked Shield",
    description: "A large shield that bites back. Adds block and spikes.",
    category: "TOOL",
    width: 2,
    height: 2,
    icon: "ShieldAlert",
    rarity: "UNCOMMON",
    triggerType: "SHIELD",
    combatStats: {
      block: 15,
      spikes: 8,
      baseCooldown: 3.5,
      energyCost: 15,
    },
    recipe: {
      ingredients: ["shard_spikes", "shard_block", "scrap_shield"],
      result: "spiked_shield",
    },
  },
  poison_shard: {
    id: "poison_shard",
    name: "Poison Shard",
    description: "A toxic fragment. Applies poison on hit.",
    category: "TOOL",
    width: 1,
    height: 3,
    icon: "Skull",
    rarity: "COMMON",
    effects: [{ type: "POISON", value: 2 }],
  },
  fire_shard: {
    id: "fire_shard",
    name: "Fire Shard",
    description: "A burning fragment. Applies burn on hit.",
    category: "TOOL",
    width: 1,
    height: 3,
    icon: "Flame",
    rarity: "COMMON",
    effects: [{ type: "FIRE", value: 2 }],
  },
  frost_shard: {
    id: "frost_shard",
    name: "Frost Shard",
    description: "A chilling fragment. Applies slow on hit.",
    category: "TOOL",
    width: 1,
    height: 3,
    icon: "Snowflake",
    rarity: "COMMON",
    effects: [{ type: "SLOW", value: 2 }],
  },
  viper_blade: {
    id: "viper_blade",
    name: "Viper Blade",
    description:
      "A toxic dagger. Poisons enemies (Hits HP only when block is 0).",
    category: "WEAPON",
    width: 1,
    height: 2,
    icon: "Sword",
    rarity: "UNCOMMON",
    triggerType: "ATTACK",
    combatStats: {
      damage: 10,
      baseCooldown: 0.9,
      energyCost: 12,
    },
    effects: [{ type: "POISON", value: 4, chance: 100 }],
    recipe: {
      ingredients: ["rusty_dagger", "poison_shard"],
      result: "viper_blade",
    },
  },
  blaze_wand: {
    id: "blaze_wand",
    name: "Blaze Wand",
    description: "A searing wand. Burns enemy block over time.",
    category: "WEAPON",
    width: 1,
    height: 2,
    icon: "Zap",
    rarity: "UNCOMMON",
    triggerType: "ATTACK",
    combatStats: {
      damage: 8,
      manaCost: 10,
      baseCooldown: 1.1,
      manaRegen: 1.5,
    },
    effects: [{ type: "FIRE", value: 8, chance: 100 }],
    recipe: {
      ingredients: ["cracked_wand", "fire_shard"],
      result: "blaze_wand",
    },
  },
  frostbound_shield: {
    id: "frostbound_shield",
    name: "Frostbound Shield",
    description: "A chilled shield. Slows down enemy actions.",
    category: "TOOL",
    width: 2,
    height: 2,
    icon: "ShieldAlert",
    rarity: "UNCOMMON",
    triggerType: "SHIELD",
    combatStats: {
      block: 20,
      baseCooldown: 3.8,
      energyCost: 12,
    },
    effects: [{ type: "SLOW", value: 3, chance: 100 }],
    recipe: {
      ingredients: ["scrap_shield", "frost_shard"],
      result: "frostbound_shield",
    },
  },
}
